export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    topLine: 'Who We Are',
    headline: 'A Respected and Dependable Trading Company ',
    description: 'Erlomaton Investment was established and registered under the companies act in 2022 and we are fully compliant with the relevant trade licences, Kenya Revenue and certified under the Access to Government Procurement Opportunities.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-1.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'generalsuplies',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Why Us',
    headline: 'Leader in the Supplies Business',
    description: 'Erlomaton Investment is a general trading company that helps clients in diverse industries to get access to all materials they require at competitively fair market prices.',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/svg-3.svg'),
    alt: 'Pulling',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'What We Do',
    headline: 'Understanding the Issues and What Needs to be Undertaken',
    description: 'At Erlomaton Investment, we have a vast network of professionals. We supply stationary materials, electrical appliances, cutlery and utensils, clothing, and food stuffs.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-2.svg'),
    alt: 'BigCart',
    dark: true,
    primary: true,
    darkText: false,
};


export const homeObjFour = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Sign Up',
    headline: 'Let\'s get you Onboarded',
    description: 'Sign Up today to get access to our exclusive offers.',
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../images/svg-4.svg'),
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjFive = {
    id: 'contactus',
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    topLine: 'Get in Touch',
    headline: 'Contact us for More Information',
    description: 'We\'d be glad to jump on a call with you ',
    buttonLabel: 'Scroll Up',
    imgStart: false,
    img: require('../../images/svg-5.svg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};